version: 2.1

workflows:
  testing:
    jobs:
      - runner
      - attaching_test:
          requires:
            - runner

jobs:
  runner:
    machine: true
    resource_class: circleci-runner/alberto-macbook
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: echo "Creating the text file" > test.txt
      - run: cat test.txt
      - persist_to_workspace:
          root: .
          paths:
            - test.txt

  attaching_test:
    machine: true
    resource_class: circleci-runner/alberto-macbook
    steps:
      - attach_workspace:
          at: .
      - run: cat test.txt
      - run: |
          if [[ `cat /tmp/test.txt` == "Creating the text file" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
