version: 2.1

workflows:
  testing:
    jobs:
      - runner
      - attaching_test:
          requires:
            - runner

jobs:
  runner:
    machine: true
    resource_class: runnertesting/al-macbook
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: sleep 120
