version: 2.1

workflows:
  testing:
    jobs:
      - runner
      - attaching_test:
          requires:
            - runner
      - build

jobs:
  runner:
    machine: true
    resource_class: runnertesting/al-macbook
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: echo "Creating the text file" > test.txt
      - run: cat test.txt
      - persist_to_workspace:
          root: .
          paths:
            - test.txt

  attaching_test:
    machine: true
    resource_class: runnertesting/al-macbook
    steps:
      - attach_workspace:
          at: .
      - run: cat test.txt
      - run: ls /tmp
      - run: pwd
      - run: ls
      - run: |
          if [[ `cat test.txt` == "Creating the text file" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

  build:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
