version: 2.1

jobs:
  test:
    machine:
        image: ubuntu-2004:202111-01
    resource_class: medium
    steps:
        - run: circleci-agent step halt

workflows:
  my-workflow:
    jobs:
      - test
